// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBL3.Data;

#nullable disable

namespace PBL3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608104650_PBL3fix5")]
    partial class PBL3fix5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PBL3.Models.Account", b =>
                {
                    b.Property<int>("IDs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("IDs");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PBL3.Models.DiemSo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiemHoiDong")
                        .HasColumnType("int");

                    b.Property<int>("DiemHuongDan")
                        .HasColumnType("int");

                    b.Property<int>("DiemPhanBien")
                        .HasColumnType("int");

                    b.Property<int>("DiemTrungBinh")
                        .HasColumnType("int");

                    b.Property<int>("DoAnId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DoAnId");

                    b.ToTable("DiemSos");
                });

            modelBuilder.Entity("PBL3.Models.DoAn", b =>
                {
                    b.Property<int>("DoAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GVHD")
                        .HasColumnType("longtext");

                    b.Property<int>("MSSV")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<int>("NamThucHien")
                        .HasColumnType("int");

                    b.Property<string>("NgayBatDau")
                        .HasColumnType("longtext");

                    b.Property<string>("NgayKetThuc")
                        .HasColumnType("longtext");

                    b.Property<int?>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Ten")
                        .HasColumnType("longtext");

                    b.Property<string>("YCGV")
                        .HasColumnType("longtext");

                    b.HasKey("DoAnId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DoAns");
                });

            modelBuilder.Entity("PBL3.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .HasColumnType("longtext");

                    b.Property<string>("Khoa")
                        .HasColumnType("longtext");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("longtext");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("PBL3.Models.SinhVien", b =>
                {
                    b.Property<int>("SinhVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .HasColumnType("longtext");

                    b.Property<string>("Khoa")
                        .HasColumnType("longtext");

                    b.Property<string>("LopHocPhan")
                        .HasColumnType("longtext");

                    b.Property<int>("MSSV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NienKhoa")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .HasColumnType("longtext");

                    b.HasKey("SinhVienId");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("PBL3.Models.TienDo", b =>
                {
                    b.Property<int>("TienDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DoAnId")
                        .HasColumnType("int");

                    b.Property<string>("Khoa")
                        .HasColumnType("longtext");

                    b.Property<string>("NgayCapNhat")
                        .HasColumnType("longtext");

                    b.Property<string>("NoiDung")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("TienDoId");

                    b.HasIndex("DoAnId");

                    b.ToTable("TienDos");
                });

            modelBuilder.Entity("PBL3.Models.DiemSo", b =>
                {
                    b.HasOne("PBL3.Models.DoAn", "DoAn")
                        .WithMany()
                        .HasForeignKey("DoAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoAn");
                });

            modelBuilder.Entity("PBL3.Models.DoAn", b =>
                {
                    b.HasOne("PBL3.Models.SinhVien", "SinhVien")
                        .WithMany("DoAn")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("PBL3.Models.TienDo", b =>
                {
                    b.HasOne("PBL3.Models.DoAn", "DoAn")
                        .WithMany("TienDo")
                        .HasForeignKey("DoAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoAn");
                });

            modelBuilder.Entity("PBL3.Models.DoAn", b =>
                {
                    b.Navigation("TienDo");
                });

            modelBuilder.Entity("PBL3.Models.SinhVien", b =>
                {
                    b.Navigation("DoAn");
                });
#pragma warning restore 612, 618
        }
    }
}
